version: '2.4' # 2.4 is the last version that supports depends_on conditions for service health
networks:
  cassandra:  # docker network where all cassandra nodes will be put in
services:
  cass4:
    image: cassandra:4.0
    container_name: cass4
    hostname: cass4
    mem_limit: 3g  # It's not strictly required, but it's better to have some memory limit
    networks:
      - cassandra
    ports:
      - "7004:7000"  # Expose native binary CQL port for your apps
    volumes:
      - ./data/cass4:/var/lib/cassandra
    environment: 
        CASSANDRA_SEEDS: "cass1"
        CASSANDRA_CLUSTER_NAME: InfiniSoft
        CASSANDRA_DC: Mars
        CASSANDRA_RACK: West
        CASSANDRA_NUM_TOKENS: 16

